src/Entity/MonVestiaire.php
<?php

namespace App\Entity;

use App\Repository\MonVestiaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MonVestiaireRepository::class)]
class MonVestiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;


    #[ORM\OneToMany(mappedBy: 'Vestiaire', targetEntity: maillot::class)]
    private Collection $Maillots;

    #[ORM\OneToOne(mappedBy: 'Vestiaire', cascade: ['persist', 'remove'])]
    private ?Member $member = null;

   

    public function __construct()
    {
        $this->Maillots = new ArrayCollection();
    }
    
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }
    
    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, maillot>
     */
    public function getMaillots(): Collection
    {
        return $this->Maillots;
    }

    public function addMaillot(maillot $maillot): static
    {
        if (!$this->Maillots->contains($maillot)) {
            $this->Maillots->add($maillot);
            $maillot->setVestiaire($this);
        }

        return $this;
    }

    public function removeMaillot(maillot $maillot): static
    {
        if ($this->Maillots->removeElement($maillot)) {
            // set the owning side to null (unless already changed)
            if ($maillot->getVestiaire() === $this) {
                $maillot->setVestiaire(null);
            }
        }

        return $this;
    }

    public function getNom(): ?Member
    {
        return $this->Nom;
    }

    public function setNom(Member $Nom): static
    {
        // set the owning side of the relation if necessary
        if ($Nom->getAssociation() !== $this) {
            $Nom->setAssociation($this);
        }

        $this->Nom = $Nom;

        return $this;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(Member $member): static
    {
        // set the owning side of the relation if necessary
        if ($member->getVestiaire() !== $this) {
            $member->setVestiaire($this);
        }

        $this->member = $member;

        return $this;
    }
    
    
    
}

src/Controller/MonVestiaireController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\MonVestiaire;
use Doctrine\Persistence\ManagerRegistry;

class MonVestiaireController extends AbstractController
{
    #[Route('/mon/vestiaire', name: 'app_mon_vestiaire')]
    public function index(managerregistry $doctrine): Response
    {
        
        $entityManager = $doctrine->getManager();
        $vestiaires = $entityManager->getRepository(MonVestiaire::class)->findAll();
        
        
        return $this->render('mon_vestiaire/index.html.twig', [
            'vestiaires' => $vestiaires,
        ]);
    }
    
    #[Route('/mon/vestiaire/{id}', name: 'vestiaire_show', requirements: ['id' => '\d+'])]
    public function show(ManagerRegistry $doctrine, $id): Response
    {
        $entity_manager = $doctrine->getManager();
        $vestiaire = $entity_manager->getRepository(MonVestiaire::class)->find($id);
        
        return $this->render('mon_vestiaire/show.html.twig', [
            'monvestiaire' => $vestiaire,
        ]);
    }
    
    
    
}

templates/mon_vestiaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MonVestiaireController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/guilhemdumas/CSC4101/projet/LeVestiaire/src/Controller/MonVestiaireController.php'|file_link(0) }}">src/Controller/MonVestiaireController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/guilhemdumas/CSC4101/projet/LeVestiaire/templates/mon_vestiaire/index.html.twig'|file_link(0) }}">templates/mon_vestiaire/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/mon_vestiaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Vestiaire{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        h1 {
            background-color: #333;
            color: #fff;
            padding: 15px;
            margin: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff;
            border: 1px solid #ddd;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            margin-bottom: 5px;
        }

        a {
            text-decoration: none;
            color: #007bff;
            font-weight: bold;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Mon Vestiaire</h1>
    <table>
        <tr>
            <th>ID</th>
            <td>{{ monvestiaire.id }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ monvestiaire.nom }}</td>
        </tr>
        <tr>
            <th>Membre</th>
            <td>{{ monvestiaire.member.nom }}</td>
        </tr>
        <tr>
            <th>Mes Maillots</th>
            <td>
                <ul>
                    {% for maillot in monvestiaire.maillot %}
                        <li><a href="{{ path('maillot_show', { 'id': maillot.id }) }}">{{ maillot }}</a></li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
    </table>
{% endblock %}